[common]
database_engine_dsn = "postgresql://runcible:@localhost/runcible_app"

[dev]
database_engine_params.echo = true
database_engine_params.connect_args.options = "-c timezone=utc"
CORS_HEADERS = "*"
CORS_METHODS = "*"
CORS_ORIGIN = "*"
CORS_MAXAGE = "86400"

[test]
database_engine_dsn = "postgresql://molten:local@localhost/test_cookiecutter"
database_engine_params.echo = false
database_engine_params.connect_args.options = "-c timezone=utc"
CORS_HEADERS = "*"
CORS_METHODS = "*"
CORS_ORIGIN = "*"
CORS_MAXAGE = "86400"